"""
AI Customer Agent — собирает данные о проекте у клиента естественным
разговором и возвращает structured fields для записи в Lead.
"""

import json
import os
from typing import List, Tuple, Dict

SYSTEM_PROMPT = """You are Tila, the friendly AI assistant for a tile installation
and remodeling company in Canada. You chat with potential customers who came
from an ad.

Your job in this conversation:
1. Sound natural, warm, and concise -- like a helpful person, not a form.
2. Collect the following fields over the course of the conversation, one or two
   at a time, never as a rigid checklist:
   - name
   - phone
   - address
   - project_type (bathroom, kitchen, floor, shower, backsplash, outdoor_patio, other)
   - room_size_sqft (approximate is fine)
   - tile_type (if they don't know, offer 2-3 popular options)
   - budget_range
   - timeline
3. If the customer pushes back on price before you have enough info, acknowledge
   the concern and explain that a photo-based estimate will be more accurate,
   then continue collecting info.
4. Once you have name, phone, and project_type at minimum, tell them you can
   generate a preliminary estimate and invite them to upload photos, then offer
   to schedule a free on-site measurement.
5. Never invent a price yourself -- the estimate is generated by a separate tool.

Respond with ONLY a JSON object, no other text, in this exact shape:
{"reply": "<your natural-language reply to show the customer>",
 "fields": {"name": null, "phone": null, "address": null, "project_type": null,
            "room_size_sqft": null, "tile_type": null, "budget_range": null,
            "timeline": null}}

Only include a field in "fields" if you actually learned it or it changed in
this turn -- omit fields you don't have new information for."""


def _call_claude(history: List[Dict[str, str]]) -> Dict:
    import anthropic

    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=500,
        system=SYSTEM_PROMPT,
        messages=history,
    )
    text = response.content[0].text.strip()
    # The model is instructed to return only JSON, but may still wrap it in
    # code fences or add stray text -- pull out the outermost {...} block.
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1 or end < start:
        raise ValueError(f"No JSON object found in model response: {text!r}")
    return json.loads(text[start:end + 1])

def get_agent_reply(history: List[Dict[str, str]], lead) -> Tuple[str, Dict[str, str]]:
    """Returns (assistant_reply_text, collected_fields_dict)."""
    if not os.getenv("ANTHROPIC_API_KEY"):
        return (
            "I'm not fully set up yet -- my AI connection is missing. "
            "Please ask the site owner to add an ANTHROPIC_API_KEY.",
            {},
        )

    try:
        data = _call_claude(history)
    except Exception as e:
        import traceback
        print(f"[customer_agent] Anthropic call failed: {e}")
        traceback.print_exc()
        return (
            "Sorry, I'm having trouble thinking right now -- could you try that again in a moment?",
            {},
        )

    reply = data.get("reply", "Could you tell me a bit more about your project?")
    fields = {k: v for k, v in (data.get("fields") or {}).items() if v}
    return reply, fields