"""
AI Customer Agent — собирает данные о проекте у клиента естественным
разговором и возвращает structured fields для записи в Lead.

Реальный вызов модели закомментирован — раскомментируй и подставь ключ,
когда подключишь Anthropic API. Сейчас функция работает как чистый
"prompt contract", чтобы фронтенд/бэкенд можно было тестировать без ключа.
"""

import json
import os
from typing import List, Tuple, Dict

SYSTEM_PROMPT = """You are Tila, the friendly AI assistant for a tile installation
and remodeling company. You chat with potential customers who came from an ad.

Your job in this conversation:
1. Sound natural, warm, and concise — like a helpful person, not a form.
2. Collect the following fields over the course of the conversation, one or two
   at a time, never as a rigid checklist:
   - name
   - phone
   - address
   - project_type (bathroom, kitchen, floor, shower, backsplash, outdoor_patio, other)
   - room_size_sqft (approximate is fine)
   - tile_type (if they don't know, offer 2-3 popular options)
   - budget_range
   - timeline
3. If the customer pushes back on price before you have enough info, acknowledge
   the concern and explain that a photo-based estimate will be more accurate,
   then continue collecting info.
4. Once you have name, phone, and project_type at minimum, tell them you can
   generate a preliminary estimate and invite them to upload photos, then offer
   to schedule a free on-site measurement.
5. Never invent a price yourself — the estimate is generated by a separate tool.

At the end of every turn, output a JSON object (never shown to the user) with
any fields you were able to extract or update from the conversation so far.
"""


def _extract_fields_naive(history: List[Dict[str, str]]) -> Dict[str, str]:
    """
    Placeholder extractor used until the real model call is wired in.
    In production this is replaced by asking the model itself to return
    structured JSON (see the commented call_llm() below), which is far more
    reliable than regex/heuristics.
    """
    collected = {}
    last_user_msgs = [m["content"] for m in history if m["role"] == "user"]
    text = " ".join(last_user_msgs).lower()

    for keyword, field_value in {
        "bathroom": ("project_type", "bathroom"),
        "kitchen": ("project_type", "kitchen"),
        "floor": ("project_type", "floor"),
        "shower": ("project_type", "shower"),
        "backsplash": ("project_type", "backsplash"),
        "patio": ("project_type", "outdoor_patio"),
    }.items():
        if keyword in text:
            collected[field_value[0]] = field_value[1]

    return collected


def get_agent_reply(history: List[Dict[str, str]], lead) -> Tuple[str, Dict[str, str]]:
    """
    Returns (assistant_reply_text, collected_fields_dict).

    Swap the body of this function for a real Anthropic API call, e.g.:

        import anthropic
        client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
        response = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=500,
            system=SYSTEM_PROMPT + "\\nRespond with: {\\"reply\\": ..., \\"fields\\": {...}}",
            messages=history,
        )
        data = json.loads(response.content[0].text)
        return data["reply"], data["fields"]
    """
    collected = _extract_fields_naive(history)

    if not lead.customer or not lead.customer.name:
        reply = (
            "Hi! I'm Tila, your AI assistant here. I'd love to help you get a "
            "free estimate — could I get your name and the best phone number to reach you?"
        )
    elif not lead.project_type or lead.project_type == "other":
        reply = (
            f"Thanks! What kind of project are we looking at — bathroom, kitchen, "
            f"floor, shower, backsplash, or outdoor patio?"
        )
    else:
        reply = (
            "Got it — that's really helpful. Could you upload a few photos of the "
            "space? That'll let me put together a much more accurate estimate for you."
        )

    return reply, collected
