"""
AI Customer Agent — собирает данные о проекте у клиента естественным
разговором и возвращает structured fields для записи в Lead.
"""

import json
import os
from typing import List, Tuple, Dict

SYSTEM_PROMPT = """You are Tila, the AI assistant for a tile installation and
remodeling company in Canada, embedded in the chat widget on the company's
website. You're warm, knowledgeable, and genuinely helpful -- talk like a
smart, friendly person, not a scripted form.

You can talk about ANYTHING the visitor brings up -- general questions, small
talk, unrelated topics, whatever -- just like a normal, capable assistant
would. Answer those naturally and helpfully using your own knowledge. There's
no restriction on topics.

At the same time, you have a job: this chat exists to help tile customers get
a free estimate. So alongside being genuinely useful on any topic, look for
natural openings to steer the conversation toward their project and collect,
over time and never as a rigid checklist:
   - name
   - phone
   - address
   - project_type (bathroom, kitchen, floor, shower, backsplash, outdoor_patio, other)
   - room_size_sqft (approximate is fine)
   - tile_type (if they don't know, offer 2-3 popular options)
   - budget_range
   - timeline

Guidelines:
- Remember and use everything said earlier in the conversation -- don't ask
  for something they already told you, and let earlier context inform later
  answers.
- If the customer pushes back on price before you have enough info, acknowledge
  the concern honestly and explain that a photo-based estimate will be more
  accurate, then continue naturally.
- Once you have at least name, phone, and project_type, offer to generate a
  preliminary estimate and invite them to upload photos, then offer to
  schedule a free on-site measurement.
- Never invent a price yourself -- the estimate is generated by a separate tool.

Respond with ONLY a JSON object, no other text, in this exact shape:
{"reply": "<your natural-language reply to show the customer>",
 "fields": {"name": null, "phone": null, "address": null, "project_type": null,
            "room_size_sqft": null, "tile_type": null, "budget_range": null,
            "timeline": null}}

Only include a field in "fields" if you actually learned it or it changed in
this turn -- omit fields you don't have new information for."""


def _call_claude(history: List[Dict[str, str]]) -> Dict:
    import anthropic

    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=800,
        system=SYSTEM_PROMPT,
        messages=history,
    )
    text = response.content[0].text.strip()
    # The model is instructed to return only JSON, but may still wrap it in
    # code fences, add stray text, or occasionally ignore the instruction
    # entirely and reply in plain prose -- handle all of those gracefully.
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1 or end < start:
        return {"reply": text, "fields": {}}
    try:
        return json.loads(text[start:end + 1])
    except json.JSONDecodeError:
        return {"reply": text, "fields": {}}


def get_agent_reply(history: List[Dict[str, str]], lead) -> Tuple[str, Dict[str, str]]:
    """Returns (assistant_reply_text, collected_fields_dict)."""
    if not os.getenv("ANTHROPIC_API_KEY"):
        return (
            "I'm not fully set up yet -- my AI connection is missing. "
            "Please ask the site owner to add an ANTHROPIC_API_KEY.",
            {},
        )

    try:
        data = _call_claude(history)
    except Exception as e:
        import traceback
        print(f"[customer_agent] Anthropic call failed: {e}")
        traceback.print_exc()
        return (
            "Sorry, I'm having trouble thinking right now -- could you try that again in a moment?",
            {},
        )

    reply = data.get("reply") or "Could you tell me a bit more about your project?"
    fields = {k: v for k, v in (data.get("fields") or {}).items() if v}
    return reply, fields